### PR TITLE
Adding a phosphor component

### PR DESCRIPTION
**Pull request by SylvainCorlay**
No need to merge, since phosphor does not have a bower.json for now.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
If this was in the upstream repo under a different branch, we could point the submodule to use this revision for our experiments with phosphor.

**Comment by takluyver** [comment]
I think we're going to stop using submodules after the big split, and just use bower to pull in dependencies.

**Comment by SylvainCorlay** [comment]
so components would become a bare repository with a bower.json?

**Comment by takluyver** [comment]
Components would go away, and the new notebook repo would have a bower.json somewhere in it. The only reason for components is so that people don't need bower to run from master, and we're planning to require several JS tools (bower, less, require) to run the notebook from master.

**Comment by Carreau** [comment]
Or it might even disapear, and be part of the build step.

**Pull request closed without merging**
